const router = require("express").Router();
const auth = require("../middleware/auth");
const controller = require("../controllers/notes.controller");
const { rewriteNoteController } = require("../controllers/notesRewrite.controller");
const { expandIdeaController } = require("../controllers/notesExpand.controller");
const { sceneBuilderController } = require("../controllers/sceneBuilder.controller");
const { summarizeNoteController } = require("../controllers/notesSummary.controller");
const { characterBuilderController } = require("../controllers/characterBuilder.controller");
const { dialogueEnhancerController } = require("../controllers/dialogueEnhancer.controller");
const { ideaGeneratorController } = require("../controllers/ideaGenerator.controller");
const { autoTitleController } = require("../controllers/autoTitle.controller");
const { autoTagsController } = require("../controllers/autoTags.controller");
const { outlineGeneratorController } = require("../controllers/outlineGenerator.controller");
const { structureDocumentController } = require("../controllers/structureDocument.contoller");
const { bulletExtractorController } = require("../controllers/bulletExtractor.controller");
const { actionItemsController } = require("../controllers/actionItems.controller");
const { academicImproveController } = require("../controllers/academicImprove.controller");
const { compareTextsController } = require("../controllers/compareTexts.controller");
const { argumentStrengthenerController } = require("../controllers/argumentStrengthener.controller");

router.post("/strengthen", auth, argumentStrengthenerController);
router.post("/compare", auth, compareTextsController);
router.post("/improve-academic", auth, academicImproveController);
router.post("/actions", auth, actionItemsController);
router.post("/bullets", auth, bulletExtractorController);
router.post("/structure", auth, structureDocumentController);
router.post("/outline", auth, outlineGeneratorController);
router.post("/auto-tags", auth, autoTagsController);
router.post("/auto-title", auth, autoTitleController);
router.post("/idea", auth, ideaGeneratorController);
router.post("/dialogue", auth, dialogueEnhancerController);
router.post("/character", auth, characterBuilderController);
router.post("/summary", auth, summarizeNoteController);
router.post("/scene", auth, sceneBuilderController);
router.post("/expand", auth, expandIdeaController);
router.post("/rewrite", auth, rewriteNoteController);
router.post("/create", auth, controller.createNote);
router.get("/all", auth, controller.getAllNotes);
router.post("/update/:id", auth, controller.updateNote);
router.delete("/delete/:id", auth, controller.deleteNote);
router.get("/:id", auth, controller.getNoteById);

module.exports = router;
